name: Snake Game

# Controlador do tempo que será feita a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 12 horas.
    - cron: "0 */12 * * *"
  
  # Permite executar na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# REGRA DE SEGURANÇA NOVA (Essencial para funcionar hoje em dia)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Puxa o repositório na versão mais recente
      - uses: actions/checkout@v3

      # Gera as imagens da cobrinha (Versão atualizada v3)
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: brunoguns17
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif

      # Joga as imagens geradas para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
